#!/bin/bash

webapps=(
  "ChatGPT|https://chatgpt.com|chrome-chatgpt.com__-Default"
  "Claude|https://claude.ai|chrome-claude.ai__-Default"
  "Calendar|https://calendar.google.com|google"
  "Docs|https://docs.google.com|google"
  "Chess|https://www.chess.com|google"
)

choice=$(printf "%s\n" "${webapps[@]}" | cut -d'|' -f1 | fuzzel --dmenu) || exit 1
[[ -z "$choice" ]] && exit 0

entry=$(printf "%s\n" "${webapps[@]}" | grep "^$choice|") || exit 1
IFS='|' read -r _ url profile <<<"$entry"

nirius focus-or-spawn -a "$profile" create-webapp "$url" "$profile"

# ~/.config/hypr/scripts/focus-or-exec "$profile" create-webapp "$url" "$profile"
