#!/bin/sh
set -eu

TPL_DIR="$HOME/misc/prompt/templates"
temp_file=""

cleanup() { [ -n "$temp_file" ] && rm -f "$temp_file"; }
trap cleanup EXIT INT TERM

sel="$(fd -t f -d 1 . "$TPL_DIR" -x basename | sk --preview "bat '$TPL_DIR/{}'")" || exit 1

temp_file="$(mktemp -t "${sel##*/}.XXXXXX.txt")"
cp -- "$TPL_DIR/$sel" "$temp_file"
nv -c 'autocmd VimLeavePre * silent update' "$temp_file"
wl-copy --trim-newline <"$temp_file" && exit 0 || {
  echo >&2 "Clipboard failed"
  exit 1
}
