#!/bin/bash
msg="$*"
target_class="zen-browser"

printf 'dispatch focuswindow class:zen\n' |
  socat - UNIX-CONNECT:"/run/user/$(id -u)/hypr/$HYPRLAND_INSTANCE_SIGNATURE/.socket.sock"

sleep 0.1

if [[ -z "$msg" ]]; then
  msg="$(cliphist list | cliphist decode | wl-copy >/dev/null && wl-paste)"
fi

wtype -M alt 1 -m alt
sleep 0.05
wtype i
sleep 0.05

printf '%s' "$msg" | wl-copy
sleep 0.05
wtype -M ctrl v -m ctrl
