#!/bin/bash
set -euo pipefail

tmp="$(mktemp -t "yazi-chooser.XXXXX")"
trap 'rm -f "$tmp"' EXIT

yazi "$@" --chooser-file="$tmp"

if [[ -s "$tmp" ]]; then
  while IFS= read -r file; do
    nvim --server /tmp/nv --remote "$file"
  done <"$tmp"
fi
